- recipe/meta.yaml
Drops the `USER` setting hack needed in staged-recipes as `USER` was not defined in the Docker container. As it is now defined, this hack can be dropped.
xref: https://github.com/conda-forge/staged-recipes/pull/477/files#diff-73b2285b9f26016fd8047c0abb4b1977R35
xref: https://github.com/conda-forge/docker-images/issues/6
xref: https://github.com/conda-forge/docker-images/pull/28
Edit: ~~Currently includes the re-rendering from PR ( https://github.com/conda-forge/spyder-feedstock/pull/2 ), but that can be removed once that PR is merged.~~ This has been rebased out.
> Drop USER hack

- recipe/meta.yaml
We dropped support for PyQt4 in this version
----
@jjhelmus, @mingwandroid, @nehaljwani, I forgot to update this pin in my last PR.
> Demand PyQt5 for Spyder 3.3

- recipe/meta.yaml
@jjhelmus, @mingwandroid, @nehaljwani, I forgot to add this selector in my previous build.
This is because `keyring`'s backend in Python 2 depends on system packages. I also added the same requirement to our wheels in Spyder 3.3.1
> Don't install keyring on Linux and Python 2

- recipe/meta.yaml
See Issue #38
This attempts to do loose version pinning with `=5` and `=0` to ensure the ipykernels 1.0 doesn't get pulled in.
XREF: https://github.com/conda-forge/spyder-kernels-feedstock/pull/17#issuecomment-424777973
Checklist
> MAINT: Change the way loose versions are pinned

- .azure-pipelines/run_docker_build.sh
- README.md
- recipe/meta.yaml
Now that there is a Qt 5.9 on conda-forge we can relax the `PyQt <5.7` restriction in this recipe. Otherwise I get an install of version 3.3.1 instead of 3.3.4. I left `<5.10` in place in case defaults updates to Qt 5.12 before conda-forge.
**I don't recommend merging yet** as there seems to be some problem with the Qt 5.9 package on conda-forge (at least for linux). I experienced [the following issue](https://gitter.im/conda-forge/conda-forge.github.io?at=5cd953f35a1d435d4633c1cf) and could not use the keyboard at all in the Spyder terminal or editor. 
As suggested by @hmaarfk, setting `export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb/` fixes the issue, but I don't think we should require that of users. Once the upstream Qt package has been fixed (see conda-forge/pyqt-feedstock#52), this …
> Allow PyQt 5.9 from conda-forge

- recipe/meta.yaml
> Pin parso to version 0.5.2 because Jedi 0.14.1 is not compatible with parso 0.6.0

- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .scripts/run_docker_build.sh
- recipe/0001-Don-t-open-script-that-starts-Spyder-at-startup.patch
- recipe/build.sh
- recipe/meta.yaml
Checklist
- This fixes line endings and executable permissions of our bash scripts. This could have been caused because 4.2.1 was released on Windows (whereas it's usually released on Linux).
- It also applies a patch that prevents opening its start script at startup in Mac. This patch will be part of our next version (see https://github.com/spyder-ide/spyder/pull/14564), but I decided to apply it now to prevent a very annoying bug.
Fixes #90.
> Some fixes for 4.2.1

- recipe/0002-Remove-PYTHONEXECUTABLE.patch
- recipe/meta.yaml
Checklist
This will be part of our next release (see https://github.com/spyder-ide/spyder/pull/14565), but I decided to include it as a patch against 4.2.1 because
- It's very small.
- It only happens in Anaconda.
- We've been trying to fix tihs problem for more than six months now.
> Patch for critical bug that prevents selecting custom interpreters in macOS

- recipe/meta.yaml
Checklist
Missing bump for the `jedi` constraint done for Spyder 5.5.0 upstream: https://github.com/spyder-ide/spyder/pull/21367
> PR: Bump `jedi` upper constraint to <0.20.0 and improve constraints for `ipython` and `pyqtwebengine` 

- recipe/post-link.sh
- recipe/spyder-menu.json
Checklist
Yet another fix:
* Fix issue with sed syntax
* Fix command quotes to accommodate bundle names with spaces for macOS
> Fix sed syntax and macOS bundle names with spaces

- recipe/bld.bat
- recipe/post-link.bat
- recipe/post-link.sh
- recipe/spyder-menu-v1.json
Checklist
Fixes: spyder-ide/spyder#21855
This change _only applies to Windows_. macOS and Linux shortcuts are unaffected.
If the version of `menuinst` is `<2`, then the v2 spec file is replaced with the v1 spec file. The Windows post link script relies on the `CONDA_PYTHON_EXE` environment variable to determine the `menuinst` version. If `CONDA_PYTHON_EXE` does not exist, then no action is taken with respect to the v1 spec file, and the v2 spec file remains.
The most likely scenario where `CONDA_PYTHON_EXE` is not available is with the use of standalone conda executables (e.g. Micromamba). Note that the existing v1 spec file in Spyder's 5.x branch is broken if it is created when installing Spyder with Micromamba. This is because there is no base reference environment. The shortcut is …
> Include a menuinst v1 spec file in case users have not updated to menuinst v2 in their base env

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_python3.10.____cpython.yaml
- .ci_support/linux_64_python3.11.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_aarch64_python3.10.____cpython.yaml
- .ci_support/linux_aarch64_python3.11.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.10.____cpython.yaml
- .ci_support/osx_64_python3.11.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.10.____cpython.yaml
- .ci_support/osx_arm64_python3.11.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .ci_support/win_64_python3.10.____cpython.yaml
- .ci_support/win_64_python3.11.____cpython.yaml
- .ci_support/win_64_python3.8.____cpython.yaml
- .ci_support/win_64_python3.9.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- azure-pipelines.yml
- build-locally.py
- conda-forge.yml
- recipe/meta.yaml
Checklist
Using `packaging.parse` in `spyder.__init__` for version normalization requires including `packaging` in `host` in order to build the `spyder` conda package.
See spyder-ide/spyder#21836
> Ensure `packaging` is included for host

- recipe/meta.yaml
- recipe/post-link.bat
- recipe/post-link.sh
Windows:
* `menuinst` <2.1.2 will use v1 json file
* `menuinst` >=2.1.2 will use v2 json file
macOS & Linux:
* `menuinst` <2.1.2, no shortcut created.
* `menuinst` >=2.1.2 will use v2 json file
Checklist
Fixes: spyder-ide/spyder#22428
> Use v1 json spec for Windows menu entry and do not create shortcut on Posix for `menuinst` less than 2.1.2

- recipe/meta.yaml
- recipe/post-link.sh
Checklist
Fixes: spyder-ide/spyder#22566
Fixes: spyder-ide/spyder#22565
* Do not check `menuinst` version for conda-based apps. This is not necessary and circumvents any inconsistencies with `CONDA_PYTHON_EXE` introduced by `constructor` at install time.
* Do not create shortcut if there is an error retrieving the `menuinst` version. This should catch any error due to `CONDA_PYTHON_EXE` or if `menuinst` is not installed.
> Fix issue where retrieving menuinst version resulted in an error

- recipe/meta.yaml
- recipe/post-link.sh
- recipe/spyder-menu.json
Change `app_user_model_id`, `StartupWMClass`, and `CFBundleIdentifier` to include Spyder major version and (possibly) environment name. This should ensure uniqueness if multiple instances of Spyder are installed. Note `CFBundleIdentifier` cannot contain underscores.
Checklist
> Update application system identifiers

- build-locally.py
- recipe/bld.bat
- recipe/meta.yaml
- recipe/post-link.bat
- recipe/spyder-menu-reset.json
- recipe/spyder-menu.json
Checklist
Address conda/menuinst#274
Fixes spyder-ide/spyder#23062
> Move Windows reset Spyder settings shortcut to a separate json file

- recipe/meta.yaml
- recipe/spyder-menu-win.json
Checklist
Fixes spyder-ide/spyder#22844
`"%*"` appears to be ineffective on Windows, and `menuinst` strips explicit quotes, e.g. `"\"%1\""`.
Upon investigating `menuinst` source code (https://github.com/conda/menuinst/blob/903ae24739b48748cb5ad60c2bf3ac1c1febfbd6/menuinst/utils.py#L159-L171), a workaround is to add a space at the end of the argument.
This ensures that the `"%1"` is double-quoted in the registry command, allowing files/paths with spaces to be handled correctly.
See conda/menuinst#290
> Ensure registry command argument is double-quoted on Windows

- .ci_support/win_64_python3.10.____cpython.yaml
- .ci_support/win_64_python3.11.____cpython.yaml
- .ci_support/win_64_python3.12.____cpython.yaml
- .ci_support/win_64_python3.9.____cpython.yaml
- .gitignore
- README.md
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
See #203.
1. Release 6.0.4rc1 to PyPi
2. Update feedstock in this PR:
* version: 6.0.4rc1
* build: 0
* sha256: _from PyPi_
3. Verify checks succeed
4. Merge this PR
5. Proceed with 6.0.4rc1 release to conda-forge and GitHub
> RC version of PR 203

- README.md
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
Checklist
Fixes #175
Fixes #178
This PR's workflows will fail until the changes in spyder-ide/spyder#23141 are propagated to PyPi.
spyder-ide/spyder#23141 can be merged anytime, since it should only impact installer builds for PRs. This PR should be merged some time after spyder-ide/spyder#23141 is merged, but immediately following upload of the PyPi package prior to a release or release candidate. Once this PR is merged, the remaining release steps can proceed.
This PR intends to create two packages from one feedstock.
* `spyder-base`: contains the `spyder` source code and specifies all of `spyder`'s dependencies *except* any direct or indirect dependence on `pyqt`.
* `spyder`: only specifies `spyder`'s direct and indirect dependencies on `pyqt`.
The intention is to provide a way for …
> Create spyder-base package that does not depend on pyqt

- recipe/meta.yaml
> PR: Move `fcitx-qt5` dependency from spyder-base to spyder

- recipe/meta.yaml
Checklist
Added `__linux` meta-package to `spyder` meta-package, due to the linux selector for `fcitx-qt5`.
> PR: Build separate spyder meta-package because of fcitx-qt5

- .scripts/run_win_build.bat
- recipe/meta.yaml
Checklist
We need to do this because we drop support for Python 3.8 in https://github.com/spyder-ide/spyder/pull/24493.
> Bump minimal supported Python version to 3.9 for 6.1.0a2

- .ci_support/linux_64_.yaml
- .ci_support/osx_64_.yaml
- recipe/meta.yaml
- recipe/post-link.bat
- recipe/post-link.sh
Checklist
To prevent user site-packages from being used in Spyder's installer runtime environment, the `site.py` module is patched via `post-link.[sh|bat]` scripts.
`PYTHONNOUSERSITE=1` or the `-s` flag are mechanisms that achieve the same thing, however, neither of these options is practical with `menuinst` on all platforms.
Fixes https://github.com/spyder-ide/spyder/issues/24773
> Patch `site.py` in spyder-runtime environment to prevent using user site-packages
