.gitattributes
.travis.yml
README.md
appveyor.yml
ci_support/run_docker_build.sh

~~I believe `OS X` will fail due to the lack of `python.app`.~~

Re-render to get Python 3.6

---

recipe/meta.yaml

Pin Jedi to 0.9

---

.travis.yml
README.md
appveyor.yml
ci_support/fast_finish_ci_pr_build.sh
ci_support/run_docker_build.sh
circle.yml
recipe/meta.yaml

@ccordoba12 I am slowly moving things to `qt/pyqt 5` can you take a look please?

Remove pins for pyqt and rope

---

recipe/meta.yaml

@mingwandroid, @jjhelmus, @nehaljwani, just letting you know guys about this one.

Update to 3.2.6

---

recipe/meta.yaml

Letting know @mingwandroid, @jjhelmus and @nehaljwani about this one.

Update to 3.2.7

---

recipe/meta.yaml

Pinging @nehaljwani, @jjhelmus and @mingwandroid about this one.

Update to 3.2.8

---

recipe/meta.yaml

Update to 3.3.1

---

.appveyor.yml
.circleci/build_steps.sh
.travis.yml
recipe/meta.yaml

Create packages for 4.0beta1

---

recipe/meta.yaml

Fix spyder-kernels requirement

---

.ci_support/linux_python2.7.yaml
.ci_support/linux_python3.6.yaml
.ci_support/linux_python3.7.yaml
.ci_support/osx_python2.7.yaml
.ci_support/osx_python3.6.yaml
.ci_support/osx_python3.7.yaml
.ci_support/win_python2.7.yaml
.ci_support/win_python3.6.yaml
.ci_support/win_python3.7.yaml
recipe/conda_build_config.yaml

@conda-forge/core, I want to upload our beta packages to the beta conda-forge channel. Is this the right way to do it?

Change main channel from main to beta

---

.ci_support/linux_python2.7.yaml
.ci_support/linux_python3.6.yaml
.ci_support/linux_python3.7.yaml
.ci_support/osx_python2.7.yaml
.ci_support/osx_python3.6.yaml
.ci_support/osx_python3.7.yaml
.ci_support/win_python2.7.yaml
.ci_support/win_python3.6.yaml
.ci_support/win_python3.7.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Update to 4.0beta3

---

recipe/meta.yaml

Update to v4.0beta7

---

recipe/meta.yaml

Update to 4.0rc1

---

.gitattributes
recipe/meta.yaml

Update to v4.0rc2

---

recipe/meta.yaml

Update to v4.0rc3

---

.gitattributes
README.md
recipe/meta.yaml
recipe/osx-zmq.patch

Update to version 4.0.0

---

recipe/meta.yaml

PR: Update psutil

---

recipe/meta.yaml

Checklist
Fixes spyder-ide/spyder#11580

Fix constraint on spyder-kernels

---

recipe/meta.yaml

Fix Jedi dependency

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_python3.6.____cpython.yaml
.ci_support/linux_64_python3.7.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.6.____cpython.yaml
.ci_support/osx_64_python3.7.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
README.md
build-locally.py
recipe/build.sh
recipe/meta.yaml

Update to 5.0a2

---

.github/CODEOWNERS
.scripts/run_docker_build.sh
README.md
recipe/meta.yaml

Update to 5.0 alpha3

---

.ci_support/linux_64_python3.6.____cpython.yaml
.ci_support/linux_64_python3.7.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
recipe/meta.yaml

Update to 5.0 alpha4

---

recipe/meta.yaml

Update to 5.0alpha5

---

.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
LICENSE.txt
README.md
recipe/meta.yaml

Update to 5.0alpha7

---

recipe/menu-windows.json
recipe/meta.yaml

Update folder start menu

---

LICENSE.txt
conda-forge.yml
recipe/meta.yaml

Checklist
Ref #124
Ref https://conda-forge.org/status/#python310

Fix provider

---

.ci_support/linux_64_python3.10.____cpython.yaml
.ci_support/linux_64_python3.11.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/linux_aarch64_python3.10.____cpython.yaml
.ci_support/linux_aarch64_python3.11.____cpython.yaml
.ci_support/linux_aarch64_python3.8.____cpython.yaml
.ci_support/linux_aarch64_python3.9.____cpython.yaml
.ci_support/osx_64_python3.10.____cpython.yaml
.ci_support/osx_64_python3.11.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.ci_support/osx_arm64_python3.10.____cpython.yaml
.ci_support/osx_arm64_python3.11.____cpython.yaml
.ci_support/osx_arm64_python3.8.____cpython.yaml
.ci_support/osx_arm64_python3.9.____cpython.yaml
.ci_support/win_64_python3.10.____cpython.yaml
.ci_support/win_64_python3.11.____cpython.yaml
.ci_support/win_64_python3.8.____cpython.yaml
.ci_support/win_64_python3.9.____cpython.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Update to version 6.0.0a1

---

recipe/post-link.bat

Checklist
@ccordoba12, sorry about this. A local git stash was accidentally included in the previous PR.

Remove local dev patch that was accidentally committed

---

recipe/meta.yaml

Update to version 6.0.0a4

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_python3.10.____cpython.yaml
.ci_support/linux_64_python3.11.____cpython.yaml
.ci_support/linux_64_python3.12.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/linux_aarch64_python3.10.____cpython.yaml
.ci_support/linux_aarch64_python3.11.____cpython.yaml
.ci_support/linux_aarch64_python3.12.____cpython.yaml
.ci_support/linux_aarch64_python3.8.____cpython.yaml
.ci_support/linux_aarch64_python3.9.____cpython.yaml
.ci_support/osx_64_python3.11.____cpython.yaml
.ci_support/osx_64_python3.12.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.ci_support/osx_arm64_python3.10.____cpython.yaml
.ci_support/osx_arm64_python3.11.____cpython.yaml
.ci_support/osx_arm64_python3.12.____cpython.yaml
.ci_support/osx_arm64_python3.9.____cpython.yaml
.ci_support/win_64_python3.10.____cpython.yaml
.ci_support/win_64_python3.11.____cpython.yaml
.ci_support/win_64_python3.12.____cpython.yaml
.ci_support/win_64_python3.8.____cpython.yaml
.ci_support/win_64_python3.9.____cpython.yaml
README.md
recipe/meta.yaml

Dependencies changes:
- `aiohttp` >=3.9.3
- `asyncssh` >=2.0.0,<3.0.0
- `spyder-kernels` >=3.0.0b6,<3.0.0b7
- `yarl` >=1.9.4
Checklist

PR: Update to version 6.0.0b1

---

.ci_support/linux_64_python3.10.____cpython.yaml
.ci_support/linux_64_python3.11.____cpython.yaml
.ci_support/linux_64_python3.12.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.scripts/build_steps.sh
README.md
recipe/meta.yaml

Dependencies changes:
- `paramiko` (removed)
Checklist

PR: Update to version 6.0.0b3

---

recipe/meta.yaml

Dependencies changes:
- `sphinx` >=0.6.6,<7.4.0
- `spyder-kernels` >=3.0.0b9,<3.0.0b10
Checklist

PR: Update to version 6.0.0rc2 

---

recipe/spyder-menu-v1.json.bak
recipe/spyder-menu.json

Create shortcut on Windows to reset Spyder preferences

---

recipe/meta.yaml

Updated dependencies:
- spyder-kernels >=3.0.1,<3.1.0
- qtconsole >=5.6.1,<5.7.0
Checklist

PR: Update to 6.0.2rc1

---

recipe/meta.yaml

Designate osx and linux on noarch builds.

---

.github/CODEOWNERS
README.md
recipe/meta.yaml

Add mrclary as administrator

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.scripts/run_win_build.bat
recipe/meta.yaml

Implement conda-forge-admin's recommendations for noarch

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.github/CODEOWNERS
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
README.md
recipe/meta.yaml

Checklist
Remove old maintainers.

Remove old maintainers

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.github/CODEOWNERS
.scripts/create_conda_build_artifacts.bat
.scripts/create_conda_build_artifacts.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
README.md
azure-pipelines.yml
build-locally.py
conda-forge.yml
recipe/bld.bat
recipe/meta.yaml
recipe/post-link.bat
recipe/spyder-menu-reset.json
recipe/spyder-menu-v1.json.bak
recipe/spyder-menu.json

Checklist
PR in preparation for the upcoming 6.0.3 release.

Update to 6.0.3rc1

---

recipe/meta.yaml
recipe/spyder-menu-win.json

PR: Additional fixes for 6.0.4rc1

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
conda-forge.yml
recipe/meta.yaml

PR: Try pinning `anaconda-client` to prevent packages upload failures

---

recipe/meta.yaml

Fix spyder-kernels version (3.1.0a1)

---

.gitignore
recipe/meta.yaml

Update to 6.0.5rc1

---

recipe/meta.yaml

Add Linux platform virtual package (`fcitx-qt5`)

---

.scripts/run_docker_build.sh
.scripts/run_win_build.bat
build-locally.py
recipe/meta.yaml

Update to 6.0.6rc1

---

recipe/meta.yaml

Update to 6.0.7rc1

---

recipe/meta.yaml

Update to 6.1.0rc1
